apiVersion: v1
kind: Service
metadata:
  name: hadoop-lb
spec:
  loadBalancerIP: 34.138.10.197
  type: LoadBalancer
  ports:
    - port: 50070
      protocol: TCP
      targetPort: 50070
  selector:
    app: app-hadoop