apiVersion: v1
kind: Service
metadata:
  name: jupyter-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.138.10.197
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: app-jupyter