apiVersion: v1
kind: Service
metadata:
  name: sonar-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.138.10.197
  ports:
    - port:  9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: app-sonar